name: "Release"
on:
  push:
    tags:
      - "*"
jobs:
  vaultTest:
    name: Execute Vault integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Go tests
        uses: ./.github/actions/test
        with:
          go-version: 1.16
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Generate release
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: "${{ env.TAG }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"